# frontend-deploy.yml
name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install test dependencies
        run: cd frontend && npm install --only=dev

      - name: Run tests
        run: cd frontend && npm test

  build-frontend:
    runs-on: ubuntu-latest

    needs: run-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build
